#pragma once

enum MainComponentType
{
    MAIN_COMPONENT_TYPE_NONE = 0,
    BLADE,
    IMU,
    ROTARY_ENCODER,
};

enum ComponentType
{
    UNKNOWN = 0,
    ROTARY_ENCODER_GENERIC,
    PUSH_BUTTON_GENERIC,
    IMU_MPU6500,
    IMU_MPU9250,
    DISPLAY_SSD1306,
    AUDIO_DFPLAYER_MINI,
    BLADE_NEOPIXEL,
    BLADE_SINGLE_LED,
    LIGHTSABER_CONTROLLER_GENERIC,
};